import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useDemoTour } from '../context/DemoTourContext'
import { datasetUrl } from '../lib/paths'
import { APP_VERSION } from '../lib/version'

type Summary = {
  version: string
  total: number
  full_uvvis: number
  ir: number
  raman: number
  catalog_only: number
  lab_set?: number
  lab_set_count?: number
  experimental?: number
  generatedAt?: string
}

export function AboutPage() {
  const { startTour } = useDemoTour()
  const [summary, setSummary] = useState<Summary | null>(null)

  useEffect(() => {
    let cancelled = false
    fetch(datasetUrl('summary.json'))
      .then((r) => (r.ok ? r.json() : null))
      .then((data: Summary | null) => {
        if (!cancelled && data) setSummary(data)
      })
      .catch(() => {
        /* optional */
      })
    return () => {
      cancelled = true
    }
  }, [])

  return (
    <main className="main page-main">
      <article className="page-panel">
        <h1 className="page-h1">About BandAtlas</h1>
        <p className="page-lead">
          BandAtlas is a static browser application for exploring small-molecule{' '}
          <strong>UV–Vis</strong>, <strong>IR</strong>, and <strong>Raman</strong> records
          alongside structures and export tools.
        </p>

        <section className="skills-panel" data-testid="skills-panel" aria-label="Builder and metrics">
          <h2 className="page-h2">Built by Nikshay Bisht</h2>
          <p>
            Solo-built teaching atlas — product framing, dataset pipeline, UI, tests, and GitHub
            Pages deploy. GitHub:{' '}
            <a href="https://github.com/nikshaybisht" target="_blank" rel="noreferrer">
              @nikshaybisht
            </a>
            {' · '}
            <a href="https://github.com/nikshaybisht/bandatlas" target="_blank" rel="noreferrer">
              bandatlas repo
            </a>
            .
          </p>
          <ul className="metrics-grid" data-testid="metrics-grid">
            <li>
              <span className="metric-val">{summary?.total ?? '—'}</span>
              <span className="metric-label">compounds</span>
            </li>
            <li>
              <span className="metric-val">{summary?.full_uvvis ?? '—'}</span>
              <span className="metric-label">full UV curves</span>
            </li>
            <li>
              <span className="metric-val">
                {summary?.lab_set ?? summary?.lab_set_count ?? '—'}
              </span>
              <span className="metric-label">lab set</span>
            </li>
            <li>
              <span className="metric-val">v{summary?.version || APP_VERSION}</span>
              <span className="metric-label">dataset / app</span>
            </li>
          </ul>
          <p className="page-muted">
            Metrics load from <code>dataset/summary.json</code> (regenerated by{' '}
            <code>npm run dataset</code>).
          </p>
          <button type="button" className="welcome-primary" onClick={startTour}>
            Run 60s tour
          </button>
        </section>

        <section className="skills-panel" aria-label="Instructors">
          <h2 className="page-h2">Instructors &amp; workshops</h2>
          <p>
            Free static app for lectures and labs — no accounts or license keys. Start at the
            in-app pack:
          </p>
          <p>
            <Link to="/instructors" className="welcome-primary" style={{ display: 'inline-block' }}>
              Open instructor pack
            </Link>
          </p>
          <ul className="page-list">
            <li>10-minute lecture plan + pin a release tag</li>
            <li>
              Top 50 curriculum ids, printable worksheet, 2-hour workshop outline (in repo{' '}
              <code>docs/</code>)
            </li>
          </ul>
        </section>

        <h2 className="page-h2">What it is</h2>
        <ul className="page-list">
          <li>A teaching and lab-discussion companion for common chromophores and solvents</li>
          <li>Searchable catalog with full UV teaching curves plus IR/Raman for every entry</li>
          <li>Honest quality tags: teaching envelope vs experimental vs schema demo</li>
          <li>
            Offline-friendly SDF structure cache for demo compounds; PubChem fallback when online
          </li>
        </ul>

        <h2 className="page-h2">What it is not</h2>
        <ul className="page-list">
          <li>
            <strong>Not</strong> a certified spectral library or instrument-grade reference archive
          </li>
          <li>
            <strong>Not</strong> a substitute for primary literature digitizations when reporting
            experimental numbers
          </li>
          <li>
            <strong>Not</strong> a backend service — everything ships as static files (GitHub Pages)
          </li>
        </ul>

        <h2 className="page-h2">Methodology</h2>
        <p>
          How teaching envelopes are built, how experimental series are accepted, and what is
          forbidden is documented in the repository methodology note.
        </p>
        <p>
          <a
            href="https://github.com/nikshaybisht/bandatlas/blob/main/docs/methodology.md"
            target="_blank"
            rel="noreferrer"
          >
            docs/methodology.md on GitHub
          </a>
          {' · '}
          <a
            href="https://github.com/nikshaybisht/bandatlas/blob/main/docs/ADD_SPECTRUM.md"
            target="_blank"
            rel="noreferrer"
          >
            Add a UV teaching seed
          </a>
        </p>

        <h2 className="page-h2">Citation</h2>
        <p className="cite-block">
          Bisht, N. <em>BandAtlas</em> (v{APP_VERSION}).{' '}
          <a href="https://github.com/nikshaybisht/bandatlas">github.com/nikshaybisht/bandatlas</a>.
          Live:{' '}
          <a href="https://nikshaybisht.github.io/bandatlas/">
            nikshaybisht.github.io/bandatlas
          </a>
          . MIT License.
        </p>
        <p className="page-muted">
          Prefer <code>CITATION.cff</code> in the repository for machine-readable citation metadata.
        </p>

        <h2 className="page-h2">Legal</h2>
        <p>
          Software is released under the <strong>MIT</strong> license. Compound identifiers and
          literature pointers belong to their respective sources; teaching envelopes are original
          model curves constrained to tabulated λ_max / group frequencies — not raw instrument
          dumps.
        </p>

        <p className="page-nav-back">
          <Link to="/">← Back to explorer</Link>
          {' · '}
          <Link to="/guide">60-second guide</Link>
          {' · '}
          <Link to="/lab">Lab companion</Link>
          {' · '}
          <Link to="/instructors">Instructors</Link>
        </p>
      </article>
    </main>
  )
}
